apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ include "my-csi-driver.fullname" . }}
spec:
  attachRequired: false
  podInfoOnMount: true
  fsGroupPolicy: File
  storageCapacity: true
  volumeLifecycleModes:
    - Persistent
