{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "my-csi-driver.fullname" . }}-controller
  labels:
    app.kubernetes.io/name: {{ include "my-csi-driver.fullname" . }}
    app.kubernetes.io/component: controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "my-csi-driver.fullname" . }}-node
  labels:
    app.kubernetes.io/name: {{ include "my-csi-driver.fullname" . }}
    app.kubernetes.io/component: node
{{- end }}
