kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
kind: Pod
apiVersion: v1
metadata:
  name: test-pod
spec:
  containers:
    - name: test-container
      image: busybox
      command:
        ["/bin/sh", "-c", "while true; do date >> /mnt/dates; sleep 2; done"]
      volumeMounts:
        - name: volume
          mountPath: "/mnt"
  restartPolicy: "Never"
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: myclaim
